# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 02:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('TI', 'Tarjeta de identidad'), ('CC', 'Cedula de ciudadan\xeda'), ('CE', 'Cedula de Extranjer\xeda'), ('NIT', 'NIT'), ('Pst', 'Pasaporte'), ('CD', 'Carnet Dipom\xe1tico')], default='CC', max_length=5, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(max_length=30, verbose_name='N\xfamero de Identificaci\xf3n')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'LGTBI')], default='M', max_length=2, verbose_name='G\xe9nero')),
                ('phone', models.CharField(max_length=30, verbose_name='Tel\xe9fono')),
                ('role', models.CharField(choices=[('A', 'Administrador'), ('AUX', 'Auxiliar'), ('END', 'Final')], max_length=1, verbose_name='Cargo')),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterGuardianship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_register_guardianship', models.CharField(max_length=20, verbose_name='Radicado')),
                ('date_of_the_decision_of_guardianship', models.DateField(verbose_name='Fecha del Fallo')),
                ('concerning', models.CharField(max_length=25, verbose_name='Accionante')),
                ('gender', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('LGTBI', 'LGTBI')], default='Masculino', max_length=2, verbose_name='G\xe9nero')),
                ('ethnic_group', models.CharField(choices=[('Mestizo - Blanco', 'Mestizo - Blanco'), ('Afro', 'Afro'), ('Rom', 'Rom'), ('Indigena', 'Indigena')], default='Mestizo - Blanco', max_length=25, verbose_name='Etnia')),
                ('condition', models.CharField(choices=[('Victima', 'V\xedctima'), ('Discapacidad', 'Discapacidad'), ('Menor', 'Menor'), ('Adulto Mayor', 'Adulto Mayor')], default='Victima', max_length=25, verbose_name='Condici\xf3n')),
                ('adult_greater', models.BooleanField(default=False)),
                ('younger', models.BooleanField(default=False)),
                ('ownName', models.BooleanField(default=False)),
                ('legal_guardian', models.BooleanField(default=False)),
                ('unofficial_agent', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=False)),
                ('pension', models.CharField(blank=True, max_length=40, null=True, verbose_name='Pensi\xf3n')),
                ('epm', models.BooleanField(default=False)),
                ('epn', models.BooleanField(default=False)),
                ('regime', models.CharField(choices=[('Subsidiado', 'Subsidiado'), ('Contributivo', 'Contributivo')], default='Subsidiado', max_length=15, verbose_name='R\xe9gimen')),
                ('which_entity', models.CharField(max_length=50, verbose_name='Cu\xe1l Entidad?')),
                ('asmet_salud', models.BooleanField(default=False)),
                ('cafe_salud', models.BooleanField(default=False)),
                ('sos', models.BooleanField(default=False)),
                ('salud_total', models.BooleanField(default=False)),
                ('nueva_eps', models.BooleanField(default=False)),
                ('pijaos_salud', models.BooleanField(default=False)),
                ('sura', models.BooleanField(default=False)),
                ('coomeva', models.BooleanField(default=False)),
                ('cosmitet', models.BooleanField(default=False)),
                ('other_eps', models.CharField(blank=True, max_length=40, null=True)),
                ('personal_integrity', models.BooleanField(default=False)),
                ('life', models.BooleanField(default=False)),
                ('human_dignity', models.BooleanField(default=False)),
                ('health', models.BooleanField(default=False)),
                ('social_security', models.BooleanField(default=False)),
                ('right_of_petition', models.BooleanField(default=False)),
                ('due_process', models.BooleanField(default=False)),
                ('vital_minimum', models.BooleanField(default=False)),
                ('work', models.BooleanField(default=False)),
                ('equality', models.BooleanField(default=False)),
                ('privacy', models.BooleanField(default=False)),
                ('free_personality_development', models.BooleanField(default=False)),
                ('healthy_environment', models.BooleanField(default=False)),
                ('habeas_data', models.BooleanField(default=False)),
                ('good_name', models.BooleanField(default=False)),
                ('education', models.BooleanField(default=False)),
                ('freedom_of_Worship', models.BooleanField(default=False)),
                ('freedom_of_expression', models.BooleanField(default=False)),
                ('other_right', models.CharField(blank=True, max_length=40, null=True, verbose_name='Cu\xe1l Derecho?')),
                ('medicament', models.BooleanField(default=False)),
                ('process', models.BooleanField(default=False)),
                ('timely_medical_appointment', models.BooleanField(default=False)),
                ('specialized_appointment', models.BooleanField(default=False)),
                ('transfers_and_travel_expenses', models.BooleanField(default=False)),
                ('prosthesis', models.BooleanField(default=False)),
                ('disability_payment', models.BooleanField(default=False)),
                ('supplies', models.BooleanField(default=False)),
                ('another_negation', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cu\xe1l Negaci\xf3n?')),
                ('grant', models.BooleanField(default=False)),
                ('improper_for', models.CharField(choices=[('Hecho superado', 'Hecho superado'), ('Da\xf1o consumado', 'Da\xf1o consumado'), ('Existe otro medio de defensa', 'Existe otro medio de defensa'), ('Otro', 'Otro')], default='Hecho superado', max_length=25, verbose_name='Improcedente')),
                ('fosyga', models.BooleanField(default=False)),
                ('fomag', models.BooleanField(default=False)),
                ('health_secretary', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
        ),
    ]
