# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SI_FTPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerguardianship',
            name='adult_greater',
            field=models.BooleanField(default=False, verbose_name='Adulto Mayor'),
        ),
        migrations.AlterField(
            model_name='registerguardianship',
            name='disability_payment',
            field=models.BooleanField(default=False, verbose_name='Pago Incapacidad'),
        ),
        migrations.AlterField(
            model_name='registerguardianship',
            name='due_process',
            field=models.BooleanField(default=False, verbose_name='Debido Proceso'),
        ),
        migrations.AlterField(
            model_name='registerguardianship',
            name='education',
            field=models.BooleanField(default=False, verbose_name='Educaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='registerguardianship',
            name='epm',
            field=models.BooleanField(default=False, verbose_name='EPM'),
        ),
        migrations.AlterField(
            model_name='registerguardianship',
            name='epn',
            field=models.BooleanField(default=False, verbose_name='EPN'),
        ),
        migrations.AlterField(
            model_name='registerguardianship',
            name='equality',
            field=models.BooleanField(default=False, verbose_name='Igualdad'),
        ),
        migrations.AlterField(
            model_name='registerguardianship',
            name='free_personality_development',
            field=models.BooleanField(default=False, verbose_name='Libre Desarrollo de la Personalidad'),
        ),
        migrations.AlterField(
            model_name='registerguardianship',
            name='freedom_of_Worship',
            field=models.BooleanField(default=False, verbose_name='Libertad de Culto'),
        ),
        migrations.AlterField(
            model_name='registerguardianship',
            name='freedom_of_expression',
            field=models.BooleanField(default=False, verbose_name='Libertad de Expresi\xf3n'),
        ),
        migrations.AlterField(
            model_name='registerguardianship',
            name='good_name',
            field=models.BooleanField(default=False, verbose_name='Buen Nombre'),
        ),
        migrations.AlterField(
            model_name='registerguardianship',
            name='grant',
            field=models.BooleanField(default=False, verbose_name='Concede'),
        ),
        migrations.AlterField(
            model_name='registerguardianship',
            name='habeas_data',
            field=models.BooleanField(default=False, verbose_name='Habeas Data'),
        ),
        migrations.AlterField(
            model_name='registerguardianship',
            name='health',
            field=models.BooleanField(default=False, verbose_name='Salud'),
        ),
        migrations.AlterField(
            model_name='registerguardianship',
            name='health_secretary',
            field=models.BooleanField(default=False, verbose_name='Secretar\xeda de Salud'),
        ),
        migrations.AlterField(
            model_name='registerguardianship',
            name='healthy_environment',
            field=models.BooleanField(default=False, verbose_name='Hambiente Sano'),
        ),
        migrations.AlterField(
            model_name='registerguardianship',
            name='human_dignity',
            field=models.BooleanField(default=False, verbose_name='Dignidad Humana'),
        ),
        migrations.AlterField(
            model_name='registerguardianship',
            name='legal_guardian',
            field=models.BooleanField(default=False, verbose_name='Mediante Apoderado'),
        ),
        migrations.AlterField(
            model_name='registerguardianship',
            name='life',
            field=models.BooleanField(default=False, verbose_name='Vida'),
        ),
        migrations.AlterField(
            model_name='registerguardianship',
            name='medicament',
            field=models.BooleanField(default=False, verbose_name='Medicamento'),
        ),
        migrations.AlterField(
            model_name='registerguardianship',
            name='other_eps',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Otra Eps'),
        ),
        migrations.AlterField(
            model_name='registerguardianship',
            name='ownName',
            field=models.BooleanField(default=False, verbose_name='En Nombre Propio'),
        ),
        migrations.AlterField(
            model_name='registerguardianship',
            name='personal_integrity',
            field=models.BooleanField(default=False, verbose_name='Integridad Personal'),
        ),
        migrations.AlterField(
            model_name='registerguardianship',
            name='privacy',
            field=models.BooleanField(default=False, verbose_name='Intimidad'),
        ),
        migrations.AlterField(
            model_name='registerguardianship',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Privada'),
        ),
        migrations.AlterField(
            model_name='registerguardianship',
            name='process',
            field=models.BooleanField(default=False, verbose_name='Procedimiento'),
        ),
        migrations.AlterField(
            model_name='registerguardianship',
            name='prosthesis',
            field=models.BooleanField(default=False, verbose_name='Protesis'),
        ),
        migrations.AlterField(
            model_name='registerguardianship',
            name='public',
            field=models.BooleanField(default=False, verbose_name='P\xfablica'),
        ),
        migrations.AlterField(
            model_name='registerguardianship',
            name='right_of_petition',
            field=models.BooleanField(default=False, verbose_name='DErecho de Petici\xf3n'),
        ),
        migrations.AlterField(
            model_name='registerguardianship',
            name='social_security',
            field=models.BooleanField(default=False, verbose_name='Seguridad Social'),
        ),
        migrations.AlterField(
            model_name='registerguardianship',
            name='specialized_appointment',
            field=models.BooleanField(default=False, verbose_name='Cita Especializada'),
        ),
        migrations.AlterField(
            model_name='registerguardianship',
            name='supplies',
            field=models.BooleanField(default=False, verbose_name='Insumos'),
        ),
        migrations.AlterField(
            model_name='registerguardianship',
            name='timely_medical_appointment',
            field=models.BooleanField(default=False, verbose_name='Cita M\xe9dica Oportuna'),
        ),
        migrations.AlterField(
            model_name='registerguardianship',
            name='transfers_and_travel_expenses',
            field=models.BooleanField(default=False, verbose_name='Traslados y Vi\xe1ticos'),
        ),
        migrations.AlterField(
            model_name='registerguardianship',
            name='unofficial_agent',
            field=models.BooleanField(default=False, verbose_name='Agente Oficioso'),
        ),
        migrations.AlterField(
            model_name='registerguardianship',
            name='vital_minimum',
            field=models.BooleanField(default=False, verbose_name='M\xednimo Vital'),
        ),
        migrations.AlterField(
            model_name='registerguardianship',
            name='work',
            field=models.BooleanField(default=False, verbose_name='Trabajo'),
        ),
        migrations.AlterField(
            model_name='registerguardianship',
            name='younger',
            field=models.BooleanField(default=False, verbose_name='Menor de edad'),
        ),
    ]
