# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SI_FTPP', '0003_auto_20161209_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerguardianship',
            name='grant',
            field=models.CharField(choices=[('1', 'Si'), ('2', 'No')], default='1', max_length=5),
        ),
    ]
