# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SI_FTPP', '0004_auto_20161209_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='document_type',
            field=models.CharField(choices=[('TI', 'Tarjeta de identidad'), ('CC', 'Cedula de ciudadan\xeda'), ('CE', 'Cedula de Extranjer\xeda'), ('NIT', 'NIT'), ('Pst', 'Pasaporte'), ('CD', 'Carnet Dipom\xe1tico')], default='CC', max_length=20, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('A', 'Administrador'), ('AUX', 'Auxiliar'), ('END', 'Consultor')], default='AUX', max_length=15, verbose_name='Cargo'),
        ),
    ]
