# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 01:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SI_FTPP', '0005_auto_20161209_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_active',
        ),
    ]
